version: "3.9"

services:
  db:
    image: postgres:15
    container_name: burrowfs-db
    env_file:
      - .env.local
    ports:
      - "6432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/migrate-tool
    env_file:
      - .env.local
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    env_file:
      - .env.local
    depends_on:
      - migrate
      - db

volumes:
  db_data: