version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: burrowfs-db
    env_file:
      - .env.local
    ports:
      - "6432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: