name: Manual BurroWFS Build

on:
  workflow_dispatch:
  push:
    branches:
      - 131-Added-github-actions-deployment

jobs:
  build:
    name: Run BurroWFS build
    uses: ./.github/workflows/docker-publish.yml
